--- # -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Site settings
name: Sahin Olut
email: lastname@cs.unc.edu
description: > # this means to ignore newlines until "url:"
  Based on [*folio](https://github.com/bogoli/-folio) design.
#footer_text: >
 # Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
 # Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
 # Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.

baseurl: 'al-folio'# the base hostname & protocol for your site
url: 'https://norveclibalikci.github.io' # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: norveclibalikci
twitter_username: norveclibalikci
linkedin_username: sahinolut
scholar_userid: GL5yzjYAAAAJ
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username

contact_note: >
  You can even add a little note about which of these is the best way to reach you.

google_analytics: UA-148483366-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Inspirations
blog_description: Good stuff

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: "Newer"
    older: "Older"

# Comments
disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons: false
enable_anchorjs: false
enable_katex: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
    # projects:
    #   output: true
    #   permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ["_pages"]
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Olut

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
